### ISSUE TITLE
Use HTML lists for citations, references and relations

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite-components#3]
Ordered HTML lists are the appropriate tags to display these lists. The `<ol` tag has a `start` attribute to start a list with pagination with a number higher than 1

**Comment by mfenner** [comment]
Don't we need a `li` tag as well?

**Comment by kjgarza** [comment]
yeah, I added it in the subcomponent

https://github.com/datacite/datacite-components/commit/bee2c5049aaa500045267eb3075d4293a81412c3

**Comment by mfenner** [comment]
How do you do numbering over multiple pages?

**Comment by kjgarza** [comment]
with  `start`  parameter:

https://github.com/datacite/datacite-components/blob/47f647cdf381cd22868020d612d9645f90984f59/src/components/LinksList.vue#L5

it's bound to the page size and the page number

One can see it working here: 
![image](https://user-images.githubusercontent.com/1092861/69414360-d7d73880-0d12-11ea-943d-da7ca54f461c.png)
